# Generated by Django 5.2 on 2025-04-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_scores', to='insights.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=100)),
                ('matched_phrase', models.CharField(max_length=255)),
                ('input_phrase', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='insights.assessment')),
            ],
        ),
    ]

# touched on 2025-05-27T15:29:05.130444Z