# Generated by Django 5.2 on 2025-04-14 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_dimensionscore_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_milestones', to='insights.assessment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_milestones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

# touched on 2025-05-27T15:29:02.328325Z
# touched on 2025-05-27T15:29:05.130283Z
# touched on 2025-05-27T15:29:07.769015Z
# touched on 2025-05-27T15:29:13.439965Z